{
"urls":[
{
"sourceName":"zhanghong仓库",
"sourceUrl":"https://raw.fastgit.org/zhanghong1983/TVBOXZY/main/2"
},
{
"sourceName":"zhanghong备用仓库",
"sourceUrl":"https://agit.ai/zhanghong/tvbox/raw/branch/master/2"
},
{
"sourceName":"666666仓库",
"sourceUrl":"https://agit.ai/66666/mao/raw/commit/0ec2c15e9a1a0df2ae6c44b4d7d7a4083d6d6f77/00/xx/0update_yuan"
},
{
"sourceName":"1号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/1/tv/update_yuan"
},
{
"sourceName":"2号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/2/tv/update_yuan"
},
{
"sourceName":"3号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/3/tv/update_yuan"
},
{
"sourceName":"4号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/4/tv/update_yuan"
},
{
"sourceName":"5号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/5/tv/update_yuan"
},
{
"sourceName":"6号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/6/tv/update_yuan"
},
{
"sourceName":"7号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/7/tv/update_yuan"
},
{
"sourceName":"8号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/8/tv/update_yuan"
},
{
"sourceName":"9号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/9/tv/update_yuan"
},
{
"sourceName":"10号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/10/tv/update_yuan"
},
{
"sourceName":"11号仓库",
"sourceUrl":"http://5.nxog.top/m/dc/api/api/11/tv/update_yuan"
},
{
"sourceName":"12号仓库","sourceUrl":"http://5.nxog.top/m/dc/api/api/12/tv/update_yuan"
},
{"sourceName":"13号仓库","sourceUrl":"http://5.nxog.top/m/dc/api/api/13/tv/update_yuan"
},
{
"sourceName":"14号仓库","sourceUrl":"http://5.nxog.top/m/dc/api/api/14/tv/update_yuan"
},
{
"sourceName":"15号仓库","sourceUrl":"http://5.nxog.top/m/dc/api/api/15/tv/update_yuan"
},
{
"sourceName":"16号仓库","sourceUrl":"http://5.nxog.top/m/dc/api/api/16/tv/update_yuan"
}
]
}